#ifndef UTILS_FLUTE_H
#define UTILS_FLUTE_H

#define CLK_SPEED 50000000 // 50MHz

extern void wait_ms(unsigned long ms);
extern void wait_s(unsigned long s);

// Location of a small block memory dedicated for:
// - 64 bit tick count (clocks since last cpu reset was completed)
// - 64 bit overlay tick count (clocks since pynq overlay was loaded)
// - 64 bit random number (generated by linear feedback shift register)
static volatile unsigned long *utils_rom = (unsigned long *)(unsigned long *)0xC0005000;
#define UTILS_ROM_TICKS_COUNT_INDEX 0
#define UTILS_ROM_OVERLAY_TICKS_COUNT_INDEX 1
#define UTILS_ROM_RANDOM_NUMBER_INDEX 2

extern unsigned long get_ticks_count();
extern unsigned long get_overlay_ticks_count();
extern unsigned long get_random_number();

#endif